[build]
  command = "pnpm build"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[functions]
  directory = "netlify/functions"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "_site/img",
    "img/og/generated"
  ]
